WebAppDETAug2022/WebAppDETAug2022/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebAppDETAug2022.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebAppDETAug2022/WebAppDETAug2022/Pages/HeloPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppDETAug2022.Services;

namespace WebAppDETAug2022.Pages
{
    public class HeloPageModel : PageModel
    {
        public Helo1 ob { get; set; }
        public string Message { get; set; }
        public void OnGet()
        {
            ob=new Helo1 ();
            Message = ob.SayHelo("Supreet");
        }
      }
    }

WebAppDETAug2022/WebAppDETAug2022/Pages/Heloweb.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppDETAug2022.Pages
{
    public class HelowebModel : PageModel
    {
        public string Message { get; set; }
        public int Discount { get; set; }
public string Cuponcode { get; set; }
    //HTTPGET
    public void OnGet()
        {
            Message = "Asp.Net Core is Rocking!!";
            Discount = 15;
            Cuponcode = "NewUser";

        }
        
        }
    }

WebAppDETAug2022/WebAppDETAug2022/Pages/IPLEvent.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppDETAug2022.Models;

namespace WebAppDETAug2022.Pages
{
    public class IPLEventModel : PageModel
    {
        public List<Ticket> Tickets { get; set; }
        public void OnGet()
        {
            Tickets = new List<Ticket>
            {
                new Ticket { Category = "PlatinumPlus", Price = 5000, MaxLimit = 200000 },
                new Ticket { Category = "Platinum", Price = 4000, MaxLimit = 300000 },
                new Ticket { Category = "Gold", Price = 3000, MaxLimit = 500000 },
                new Ticket { Category = "Silver", Price = 2000, MaxLimit = 500000 },
                new Ticket { Category = "General", Price = 800, MaxLimit = 100000 }
            };

        
        }
    }
}

WebAppDETAug2022/WebAppDETAug2022/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppDETAug2022.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebAppDETAug2022/WebAppDETAug2022/Pages/PizzaPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebAppDETAug2022.Models;
using WebAppDETAug2022.Services;

namespace WebAppDETAug2022.Pages
{
    public class PizzaModel : PageModel
    {
        public List<Pizza> pizzas = new();
        [BindProperty]
        public Pizza NewPizza { get; set; } = new();

        public void OnGet()
        {
            pizzas = PizzaServices.GetAll();
        }

        public string GlutenFreeText(Pizza pizza)
        {
            return pizza.IsGlutenFree ? "Gluten Free" : "Not Gluten Free";
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            PizzaServices.Add(NewPizza);
            return RedirectToAction("Get");
        }

        public IActionResult OnPostDelete(int id)
        {
            PizzaServices.Delete(id);
            return RedirectToAction("Get");
        }
    }
}

WebAppDETAug2022/WebAppDETAug2022/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebAppDETAug2022.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebAppDETAug2022/WebAppDETAug2022/Pages/HeloPage.cshtml
@page
@model WebAppDETAug2022.Pages.HeloPageModel
@{
}
This page says @Model.Message 

WebAppDETAug2022/WebAppDETAug2022/Pages/Heloweb.cshtml
@page
@model WebAppDETAug2022.Pages.HelowebModel
@{
}
<h2>Welcome to my site!</h2>
<h3>Happy @DateTime.Today.DayOfWeek !!</h3>


Page Says @Model.Message
<p>@@Username</p>
<p>Discount for today @Model.Discount%</p>
<p>Cuponcode is @Model.Cuponcode</p>
<h5>Offer Valid Till @DateTime.Today.AddDays(3)</h5> 
<a href="mailto:Support@contoso.com">Support@contoso.com</a>

@{
    string message = "foreignObject example with Scalable Vector Graphics (SVG)";
}


<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="0" rx="10" ry="10" width="200" height="200" stroke="black"
          fill="none" />
    <foreignObject x="20" y="20" width="160" height="160">
        <p>@message</p>
    </foreignObject>
</svg>

WebAppDETAug2022/WebAppDETAug2022/Pages/IPLEvent.cshtml
@page
@using WebAppDETAug2022.Models
@model WebAppDETAug2022.Pages.IPLEventModel
@{
}
<h1>Welcome to IPL 2022!!</h1> 
<h2>Ticket Details</h2> 
<table border="2">
<tr>
<th>Category</th> 
<th>Price</th> 
<th>MaxLimit</th> 
</tr>

@foreach(Ticket t in @Model.Tickets)
{
<tr>
<td>@t.Category</td>
<td>@t.Price</td> 
<td>@t.MaxLimit</td> 
</tr> 
}
</table> 

WebAppDETAug2022/WebAppDETAug2022/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAppDETAug2022/WebAppDETAug2022/Pages/PizzaPage.cshtml
@page
@using WebAppDETAug2022.Models
@using WebAppDETAug2022.Services

@model WebAppDETAug2022.Pages.PizzaModel
@{
    ViewData["Title"] = "Pizza List";
}
<h1>Pizza List 🍕</h1>
<form method="post" class="card p-3">
    <div class="row">
        <div asp-validation-summary="All"></div>
    </div>
    <div class="form-group mb-0 align-middle">
        <label asp-for="NewPizza.Name">Name</label>
        <input type="text" asp-for="NewPizza.Name" class="mr-5">
        <label asp-for="NewPizza.Size">Size</label>
        <select asp-for="NewPizza.Size" asp-items="Html.GetEnumSelectList<PizzaSize>()" class="mr-5"></select>
        <label asp-for="NewPizza.Price"></label>
        <input asp-for="NewPizza.Price" class="mr-5" />
        <label asp-for="NewPizza.IsGlutenFree">Gluten Free</label>
        <input type="checkbox" asp-for="NewPizza.IsGlutenFree" class="mr-5">
        <button class="btn btn-primary">Add</button>
    </div>
</form>
<table class="table mt-5">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Size</th>
            <th scope="col">Gluten Free</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    @foreach (var pizza in Model.pizzas)
    {
        <tr>
            <td>@pizza.Name</td>
            <td>@($"{pizza.Price:C}")</td>
            <td>@pizza.Size</td>
            <td>@Model.GlutenFreeText(pizza)</td>
            <td>
                <form method="post" asp-page-handler="Delete" asp-route-id="@pizza.Id">
                    <button class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}